### ISSUE TITLE
QPS test result is not accurate!

### ISSUE THREAD

**Issue by chenzx** [parkghost/gohttpbench#5]
I use gohttpbench to test my service on windows laptop which run all in-memory, and it gives a QPS ~1200. (i choose gohttpbench because it can give 99% latency value)

Then i use https://github.com/codesenberg/bombardier , which measures a better QPS, as ~6000.

So there is a bug in gohttpbench?

**Comment by parkghost** [comment]
I guess you didn't use keepalive(-k), you can compare and see the effect after it is enabled.

**Comment by chenzx** [comment]
i retested with -k (keep-alive) option, and now it gets a mean QPS ~4000 compared to previous 1200. A big win! (i thought this should be clearly documented because it's indeed important!)

but i compare it with bombardier, which gives a avg 4500 and max 5200, which is both better than gohttpbench, maybe it's due to fasthttp library that bombardier uses?
